dnsmgr/token/forms.py
"""
Copyright (C) 2025 Bengt Giger

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
from flask_login import current_user
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, HiddenField, TextAreaField
from wtforms.validators import DataRequired, Length
from duration_parser import parse
from dnsmgr.models import Token


class AddForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired(), Length(min=1, max=64)])
    description = StringField("Description (optional)")
    user_id = HiddenField()
    expiration = StringField(
        "Lifetime",
        default="1y",
        validators=[DataRequired()],
        description="i.e. 30s, 1m, 1h, 1y",
    )
    submit = SubmitField("Generate")

    def __init__(self, *args, **kwargs):
        FlaskForm.__init__(self, *args, **kwargs)
        self.title = "Add token"

    def validate(self, extra_validators=None):
        FlaskForm.validate(self, extra_validators)
        try:
            parse(self.expiration.data)
        except ValueError:
            self.expiration.errors.append("Invalid time specification")
            return False

        token = Token.query.filter(
            Token.user_id == current_user.id, Token.name == self.name.data
        ).count()
        if token:
            self.name.errors.append("You already have a token of that name")
            return False
        return True


class DeleteForm(FlaskForm):
    token_id = HiddenField()
    submit = SubmitField("Delete")

    def __init__(self, *args, **kwargs):
        FlaskForm.__init__(self, *args, **kwargs)
        self.title = "Delete token"


class ShowForm(FlaskForm):
    id = HiddenField()
    token = TextAreaField(render_kw={"readonly": True, "rows": 4, "cols": 80})

dnsmgr/token/__init__.py
"""
Copyright (C) 2025 Bengt Giger

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
"""
Blueprint for the management of user authentication tokens. Tokens can be created
and deleted, but not edited.
"""
from flask import Blueprint

token_blueprint = Blueprint("token", __name__, template_folder="templates")
from . import routes  # noqa: F401

dnsmgr/token/routes.py
"""
Copyright (C) 2025 Bengt Giger

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
from flask import (
    render_template,
    request,
    flash,
    redirect,
    url_for,
    current_app as app,
)
from flask_login import login_required, current_user
from duration_parser import parse
from dnsmgr import db
from dnsmgr.models import Token, User
from dnsmgr.cryptography.auth_token import AuthToken
from . import token_blueprint
from .forms import AddForm, DeleteForm, ShowForm


@token_blueprint.route("/token_list", methods=["GET"])
@login_required
def token_list():
    context = {}

    user = User.query.filter_by(id=current_user.id).first()
    context["token_list"] = Token.query.filter_by(user_id=user.id)
    context["user"] = current_user
    context["breadcrumbs"] = [{"target": url_for("network.index"), "label": "Networks"}]

    return render_template("token/index.html", context=context)


@token_blueprint.route("/token/add", methods=["GET", "POST"])
@login_required
def add():
    context = {
        "breadcrumbs": [{"target": url_for("token.token_list"), "label": "Token list"}]
    }
    # Add form uses AuthToken
    context["token"] = AuthToken(
        secret=app.config["SECRET_KEY"], user_id=current_user.id
    )
    context["form"] = AddForm(obj=context["token"])
    if request.method == "POST" and context["form"].validate_on_submit():
        # Token user ID must match current user ID
        if context["token"].user_id != current_user.id:
            flash("Token has an invalid user ID", "error")  # pragma: no cover
            return render_template("token/add.html", context=context)
        context["form"].populate_obj(context["token"])
        # Form validation rejects this, but functional tests bypass form
        if context["form"].expiration.data == "":
            flash("Invalid time specification", "error")  # pragma: no cover
            return render_template(
                "token/add.html", context=context
            )  # pragma: no cover

        # Show form uses Token
        context["token"] = Token(
            name=context["form"].name.data,
            expiration_sec=parse(context["form"].expiration.data),
            user_id=context["token"].user_id,
            data=context["token"].data,
            description=context["form"].description.data,
        )
        db.session.add(context["token"])
        try:
            db.session.commit()
        # should not fail after proper form validation. But hardware may fail...
        except Exception:  # pragma: no cover
            flash("Could not add token", "error")  # pragma: no cover
            return render_template(
                "token/add.html", context=context
            )  # pragma: no cover

        return redirect(url_for("token.show", token_id=context["token"].id))
        # return render_template("token/show.html", context=context)

    return render_template("token/add.html", context=context)


@token_blueprint.route("/token/show/<int:token_id>", methods=["GET"])
@login_required
def show(token_id):
    context = {}
    context = {
        "breadcrumbs": [{"target": url_for("token.token_list"), "label": "Token list"}]
    }
    context["token"] = Token.query.filter_by(id=token_id).first()
    context["form"] = ShowForm(obj=context["token"])
    # return redirect(url_for("token.show"))
    return render_template("token/show.html", context=context)


@token_blueprint.route("/token/delete/<string:token_id>", methods=["GET", "POST"])
@login_required
def delete(token_id):
    context = {
        "breadcrumbs": [{"target": url_for("token.token_list"), "label": "Token list"}]
    }
    context["token"] = Token.query.filter_by(id=token_id).first()

    context["form"] = DeleteForm(obj=context["token"])
    if request.method == "POST":
        db.session.delete(context["token"])
        db.session.commit()

        return redirect(url_for("token.token_list", context=context))

    return render_template("token/delete.html", context=context)  # pragma: no cover

dnsmgr/token/templates/token/add.html
{% extends "base.html" %}

{% block content %}

    <form action="" method="post">
        <div class="d-flex justify-content-between">
            <h2>{{ context['form'].title }}</h2>
            <div>{{ context['form'].submit(class_="btn btn-primary") }}</div>
        </div>
        {{ context['form'].hidden_tag() }}
        <div class="row">
            <div class="col">
                {{ context['form'].name.label }}
                {{ context['form'].name(class_="form-control") }}
                {% for error in context['form'].name.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>
            <div class="col">
                {{ context['form'].expiration.label }}
                {{ context['form'].expiration(class_="form-control", data_toggle="tooltip", title=context['form'].expiration.description) }}
                {% for error in context['form'].expiration.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>
        </div>
        <div class="row">
            <div class="col">
                {{ context['form'].description.label }}
                {{ context['form'].description(class_="form-control") }}
                {% for error in context['form'].description.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>
        </div>
    </form>
{% endblock %}

dnsmgr/token/templates/token/delete.html
{% extends "base.html" %}

{% block content %}
    <h2>{{ context['form'].title }}</h2>

    <form action="" method="post">
        {{ context['form'].hidden_tag() }}
        <p>
            Delete token {{ context['token'].name }}?
        </p>
        <p>{{ context['form'].submit(class_="btn btn-danger") }}</p>
    </form>

{% endblock %}

dnsmgr/token/templates/token/index.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="d-flex justify-content-between">
            <h2>Your token list</h2>
            <div><a class="btn btn-primary" href="{{ url_for('token.add', user_id=0) }}">Add token</a></div>
        </div>
    </div>

    <div class="col">
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Created</th>
                    <th>Expires</th>
                    <th>Description</th>
                    <th>&nbsp</th>
                </tr>
            </thead>
            <tbody>
                {% for token in context['token_list'] %}
                <tr>
                    <td>{{ token.name }}</td>
                    <td>{{ token.creation_date_fmt() }}</td>
                    {% if token.has_expired() %}
                        {% set tooltip = "Token is valid" %}
                        {% set icon = '<i class="far fa-solid fa-square-check valid"></i>' %}
                    {% else %}
                        {% set tooltip = "Token has expired" %}
                        {% set icon = '<i class="far fa-solid fa-square-xmark invalid"></i>' %}
                    {% endif %}
                    <td data-toggle="tooltip" title="{{ tooltip }}">
                        {{ icon|safe }} {{ token.expiration_date_fmt() }}
                    </td>
                    <td>{{ token.description }}</td>
                    <td align="right">
                        <a href="{{ url_for('token.delete', token_id=token.id) }}"><i class="far fa-trash-alt delete"></i></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

dnsmgr/token/templates/token/show.html
{% extends "base.html" %}

{% block content %}
    <h2>New Access Token</h2>

    <p>This is your new token <i>{{ context["token"].name }}</i>. It won't be shown again, copy it now.</p>

    <form action="" method="post">
        {{ context['form'].hidden_tag() }}
        {{ context['form'].token }}
    </form>

{% endblock %}